version: '3.4'

services:
  

    marketsql:
        container_name: marketsql
        image: mysql:latest
        volumes:
            - ./mydir:/mydir
            - ./datadir:/var/lib/mysql
            - ./conf/my.cnf:/etc/my.cnf
            # restore database file
            - /docker/mysql/source:/docker-entrypoint-initdb.d
        environment:
            - "MYSQL_ROOT_PASSWORD=Abcd1234!!!!"                 
        ports:
            - 3306:3306
        restart: on-failure
        networks: 
            - marketnet
            
    rabbitmq:       
        container_name: rabbitmq
        image: rabbitmq:3.8.7-management
        ports: 
            - 15672:15672
            - 5672:5672
        networks: 
            - marketnet

    marketmanagement:        
        container_name: marketmanagement
        build:
            context: .
            dockerfile: Dockerfile        
        ports:
            - 8088:80
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        networks: 
            - marketnet         
        depends_on:
            - marketsql
networks:
    marketnet:
        external: false