version: '3.4'

services:

    marketmanagement:
        image: marketmanagement
        build:
            context: .
            dockerfile: Dockerfile        
        ports:
            - 8080:80
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
    marketsql:
        image: microsoft/mssql-server-linux
        environment: 
            - ACCEPT_EULA=Y
            - 'SA_PASSWORD=Abcd1234!!!!'
        ports:
            - 1433:1433
            
    rabbitmq:
        image: rabbitmq:3.8.7-management
        ports: 
            - 15672:15672
            - 5672:5672
