version: '3.4'

services:
    marketmanagement:        
        container_name: marketmanagement
        build:
            context: .
            dockerfile: Dockerfile        
        ports:
            - 8088:80
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        networks: 
            - marketnet

    marketsql:        
        container_name: marketsql
        image: mcr.microsoft.com/mssql/server:2019-latest
        environment: 
            - ACCEPT_EULA=Y
            - 'SA_PASSWORD=Abcd1234!!!!'
        ports:
            - 1433:1433  
        networks:
            - marketnet
        restart: on-failure
            
    rabbitmq:       
        container_name: rabbitmq
        image: rabbitmq:3.8.7-management
        ports: 
            - 15672:15672
            - 5672:5672
        networks: 
            - marketnet
networks:
    marketnet:
        external: true