name: Deploy Market Management

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore MarketManagement/MarketManagement.csproj
    - name: Build
      run: dotnet build MarketManagement/MarketManagement.csproj
    - name: Test
  
